-- Initial schema for the School ERP MVP.
-- All tables use BIGINT identity PKs, TIMESTAMPTZ timestamps, and reserve school_id
-- for future multi-tenancy. CITEXT is used for case-insensitive usernames.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE school (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    address         VARCHAR(500),
    phone           VARCHAR(64),
    logo_url        VARCHAR(500),
    principal_name  VARCHAR(200),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE academic_year (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id    BIGINT NOT NULL REFERENCES school(id),
    name         VARCHAR(32) NOT NULL,
    start_date   DATE NOT NULL,
    end_date     DATE NOT NULL,
    is_current   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (school_id, name)
);
CREATE INDEX idx_academic_year_school ON academic_year(school_id);

CREATE TABLE class (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id      BIGINT NOT NULL REFERENCES school(id),
    name           VARCHAR(64) NOT NULL,
    display_order  INT NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (school_id, name)
);
CREATE INDEX idx_class_school ON class(school_id);

CREATE TABLE section (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id          BIGINT NOT NULL REFERENCES class(id),
    academic_year_id  BIGINT NOT NULL REFERENCES academic_year(id),
    name              VARCHAR(16) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (class_id, academic_year_id, name)
);
CREATE INDEX idx_section_class ON section(class_id);
CREATE INDEX idx_section_year ON section(academic_year_id);

CREATE TABLE subject (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id   BIGINT NOT NULL REFERENCES school(id),
    name        VARCHAR(120) NOT NULL,
    code        VARCHAR(32)  NOT NULL,
    max_marks   INT NOT NULL DEFAULT 100,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (school_id, code)
);
CREATE INDEX idx_subject_school ON subject(school_id);

CREATE TABLE class_subject (
    class_id    BIGINT NOT NULL REFERENCES class(id) ON DELETE CASCADE,
    subject_id  BIGINT NOT NULL REFERENCES subject(id) ON DELETE CASCADE,
    PRIMARY KEY (class_id, subject_id)
);
CREATE INDEX idx_class_subject_subject ON class_subject(subject_id);

CREATE TABLE role (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO role (name) VALUES ('ADMIN'), ('TEACHER');

CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       BIGINT NOT NULL REFERENCES school(id),
    username        CITEXT NOT NULL,
    password_hash   VARCHAR(120) NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    role_id         BIGINT NOT NULL REFERENCES role(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (school_id, username)
);
CREATE INDEX idx_user_school ON app_user(school_id);
CREATE INDEX idx_user_role ON app_user(role_id);

CREATE TABLE teacher (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id    BIGINT NOT NULL REFERENCES school(id),
    user_id      BIGINT REFERENCES app_user(id),
    first_name   VARCHAR(120) NOT NULL,
    last_name    VARCHAR(120) NOT NULL,
    employee_no  VARCHAR(64),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (school_id, employee_no)
);
CREATE INDEX idx_teacher_school ON teacher(school_id);
CREATE INDEX idx_teacher_user ON teacher(user_id);

CREATE TABLE student (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id       BIGINT NOT NULL REFERENCES school(id),
    section_id      BIGINT NOT NULL REFERENCES section(id),
    admission_no    VARCHAR(64) NOT NULL,
    first_name      VARCHAR(120) NOT NULL,
    last_name       VARCHAR(120) NOT NULL,
    dob             DATE,
    gender          VARCHAR(16),
    roll_no         INT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (school_id, admission_no)
);
CREATE INDEX idx_student_school ON student(school_id);
CREATE INDEX idx_student_section ON student(section_id);

CREATE TABLE exam (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id         BIGINT NOT NULL REFERENCES school(id),
    academic_year_id  BIGINT NOT NULL REFERENCES academic_year(id),
    name              VARCHAR(120) NOT NULL,
    start_date        DATE,
    end_date          DATE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (school_id, academic_year_id, name)
);
CREATE INDEX idx_exam_school ON exam(school_id);
CREATE INDEX idx_exam_year ON exam(academic_year_id);

CREATE TABLE mark_entry (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          BIGINT NOT NULL REFERENCES student(id),
    exam_id             BIGINT NOT NULL REFERENCES exam(id),
    subject_id          BIGINT NOT NULL REFERENCES subject(id),
    marks_obtained      NUMERIC(6,2) NOT NULL,
    max_marks           INT NOT NULL,
    entered_by_user_id  BIGINT REFERENCES app_user(id),
    entered_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (student_id, exam_id, subject_id)
);
CREATE INDEX idx_mark_student ON mark_entry(student_id);
CREATE INDEX idx_mark_exam ON mark_entry(exam_id);
CREATE INDEX idx_mark_subject ON mark_entry(subject_id);
