-- Teacher assignments (which sections/subjects a teacher may teach, and class-teacher flag)
-- and daily attendance records.

CREATE TABLE teacher_assignment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id        BIGINT NOT NULL REFERENCES teacher(id) ON DELETE CASCADE,
    section_id        BIGINT NOT NULL REFERENCES section(id) ON DELETE CASCADE,
    subject_id        BIGINT REFERENCES subject(id) ON DELETE CASCADE,
    is_class_teacher  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (teacher_id, section_id, subject_id)
);
CREATE INDEX idx_teacher_assignment_teacher ON teacher_assignment(teacher_id);
CREATE INDEX idx_teacher_assignment_section ON teacher_assignment(section_id);
CREATE INDEX idx_teacher_assignment_subject ON teacher_assignment(subject_id);

CREATE TABLE attendance_record (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   BIGINT NOT NULL REFERENCES student(id) ON DELETE CASCADE,
    section_id   BIGINT NOT NULL REFERENCES section(id),
    date         DATE NOT NULL,
    status       VARCHAR(16) NOT NULL,
    remark       VARCHAR(300),
    marked_by_user_id  BIGINT REFERENCES app_user(id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (student_id, date)
);
CREATE INDEX idx_attendance_section_date ON attendance_record(section_id, date);
CREATE INDEX idx_attendance_student ON attendance_record(student_id);
